// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheetApproval.Persistence.Contexts;

namespace TimeSheetApproval.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.People", b =>
                {
                    b.Property<long>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<string>("PeopleFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeopleLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PeopleId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.Timesheet", b =>
                {
                    b.Property<long>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PeopleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimesheetDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TssTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkFromTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkToTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WorkTotalTime")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("TimesheetId");

                    b.HasIndex("PeopleId");

                    b.HasIndex("TssTypeId")
                        .IsUnique();

                    b.ToTable("Timesheet");
                });

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.TimesheetsStatusTypes", b =>
                {
                    b.Property<long>("TssTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TssTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TssTypeId");

                    b.ToTable("TimesheetsStatusTypes");
                });

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.Timesheet", b =>
                {
                    b.HasOne("TimeSheetApproval.Domain.Entities.People", "People")
                        .WithMany("Timesheets")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TimeSheetApproval.Domain.Entities.TimesheetsStatusTypes", "TimesheetsStatusTypes")
                        .WithOne("Timesheets")
                        .HasForeignKey("TimeSheetApproval.Domain.Entities.Timesheet", "TssTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("People");

                    b.Navigation("TimesheetsStatusTypes");
                });

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.People", b =>
                {
                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("TimeSheetApproval.Domain.Entities.TimesheetsStatusTypes", b =>
                {
                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
